version: "3.8"
services:
    rutorrent:
        image: linuxserver/rutorrent:latest
        deploy:
            replicas: 1
            update_config:
              parallelism: 2
              delay: 10s
            restart_policy:
                condition: on-failure
        ports:
            - 8080:80
            - 5000:5000
            - 51413:51413
            - 6881:6881/udp
        environment:
            - PUID:1000
            - PGID:1000